# Copyright (C) The uOFW team
# See the file COPYING for copying permission.

TARGET = vaudio
OBJS = vaudio.o

LIBDIR  = ./libs
LIBS = -lsceMeCore_driver -lUtilsForKernel -lInitForKernel -lSysMemForKernel -lThreadManForKernel -lsceAudio_driver

include ../../lib/build.mak
